// src/react/views/wel/index.jsx
import './index.scss'
import React, { useState } from 'react'

let timer = null // 定时器控制进度条
let totalTime = 3000 // 设定视频播放时常
const Home = () => {
  // const [progress, setProgress] = useState(0) // 进度
  const [isPlay, setIsPlay] = useState(false) // 控制播放暂停
  const [type, setType] = useState(0)
  const [count, setCount] = useState(0)

  const handlerProgress = (pre) => {
    console.log(pre)
    if (pre < 100) return pre + 1
    else {
      alert('播放结束')
      return 0
    }
  }

  // 播放暂停
  const handleVideo = () => {
    setIsPlay(!isPlay)
    // isPlay ? clearInterval(timer) : timer = setInterval(() => setProgress(handlerProgress), totalTime / 100)
  }

  const replay = () => {
    setIsPlay(true)
    setType(type ? 0 : 1)
    // if (timer) clearInterval(timer)
    // setProgress(0)
    // timer = setInterval(() => setProgress(handlerProgress), totalTime / 100)
  }
  const end = () => {
    setCount(count + 1)
    replay()
  }
  return (
    <div>
      <button onClick={ handleVideo }>{ isPlay ? '暂停' : '播放1' }</button>
      <button onClick={ replay }>重播</button>
      <span>{ `播放次数为：${count}` }</span>
      <div className="progress-box">
        {/* <div className="progress" style={{ width: `${progress}%` }}/> */}
        <div
          className={ `progress ${ isPlay ? 'play' : 'pause' }` }
          style={{
            animationDuration: `${totalTime}ms`,
            animationName: `${type ? 'replay' : 'play'}`
          }}
          onAnimationEnd={end}
        >

        </div>
      </div>
    </div>
  )
}

export default Home

// src/vue/views/wel/index.vue
<template>
  <div>
    <button @click="handleVideo">{{ isPlay ? '暂停' : '播放' }}</button>
    <button @click="replay">重播</button>
    <div class="progress-box">
      <!-- <div class="progress" :style="{ width: `${progress}%`}"/> -->
      <div 
        :class="{ 'progress': true, 'play': isPlay, 'pause': !isPlay }"
        
      >

      </div>
    </div>
  </div>
</template>
<script>
import { ref } from 'vue'
let timer = null // 定时器控制进度条
let totalTime = 3000 // 设定视频播放时常
export default {
  setup() {
    const isPlay = ref(false)
    const type = ref(0)
    const progress = ref(0)
    const setProgress = () => {
      if (progress.value < 100) progress.value += 1
      else {
        // alert('播放结束')
        progress.value = 0
      }
    }
    const handleVideo = () => {
      isPlay.value = !isPlay.value
      // console.log(isPlay.value, 'isPlay>>>')
      // !isPlay.value ? clearInterval(timer) : timer = setInterval(() => setProgress(), totalTime / 100)
    }
    const replay = () => {
      // clearInterval(timer)
      isPlay.value = true
      type.value = type.value ? 0 : 1
      console.log(type.value)
      // progress.value = 0
      // timer = setInterval(() => setProgress(), totalTime / 100)
    }
    return {
      isPlay,
      type,
      progress,
      totalTime,
      handleVideo,
      replay
    }
  }
}
</script>
<style lang="scss" scoped>
  .progress-box {
    height: 10px;
    width: 500px;
    border-radius: 5px;
    border: 1px solid black;
    .progress {
      height: 100%;
      width: 0;
      background-color: red;
      // animation: play 3s linear;
      animation-timing-function: linear;
      animation-name: play;
      animation-duration: 3000ms;
    }
  }
  .progress.play {
    animation-play-state: running;
  }
  .progress.pause {
    animation-play-state: paused;
  }
  @keyframes play {
    to {
      width: 100%;
    }
  }
  @keyframes replay {
    to {
      width: 100%;
    }
  }
</style>
